# Generated by Django 4.0.4 on 2022-05-26 13:56

import authapp.services.user_avatars_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authapp.services.user_avatars_path.users_avatars_path),
        ),
    ]
