# Generated by Django 4.0.4 on 2022-06-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
    ]
