# Generated by Django 4.0.4 on 2022-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Обновлена')),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('intro', models.CharField(max_length=1024, verbose_name='Вступление')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Markdown')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
