# Generated by Django 4.0.4 on 2022-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_Lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Обновлена')),
                ('deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('birth_day', models.DateField(verbose_name='Дата рождения')),
                ('course', models.ManyToManyField(to='mainapp.courses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
