# Generated by Django 4.0.4 on 2022-05-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_contacts_options_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
