# Generated by Django 4.0.4 on 2022-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='courseteachers',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='news',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
    ]
